### ISSUE TITLE
Integrate Map Functions into Observable Notebook

### ISSUE THREAD

**Issue by nwebb-roux** [cs7290/stinky#12]
Working Fly To with public school data filtered to arbitrary distance from Portland: https://observablehq.com/d/b9e12b358c4f1ee3

**Comment by nwebb-roux** [comment]
### Functions to Integrate Directly Into Observable Notebook
- Fly To

**Comment by bergsalex** [comment]
@nwebb-roux is this issue now open for the taking? Putting some time in today so if this needs effort I'm happy to give it a go.

**Comment by nwebb-roux** [comment]
@bergsalex Yeah, I think it would be great to get everything integrated into the notebook that's feeding the live site. I'll do the Fly To feature since that will only take me a minute, but anything else you can bring in, I say go for it!

**Comment by nwebb-roux** [comment]
@bergsalex If you wouldn't mind pinging me when the public location data is integrated into the up-to-date notebook, then I can add the Fly To function. Thanks!

**Comment by bergsalex** [comment]
@nwebb-roux, I think I got confused and mixed up our notebooks. I thought that [this notebook](https://observablehq.com/d/0f11e85a1dccddcc) was the one we're using, but it does not seem to be.

Should I apply the changes you made in that fork back to the original one?

**Comment by nwebb-roux** [comment]
Yeah, sorry for the confusion! I made that fork when I wasn’t sure what was happening with the version numbers. If you bring the changes from that notebook into the original one, it should work neatly. There are a couple new cells (parsing the geojson data in a couple different ways, plus the dropdown control itself), and a few new lines in the map JavaScript.

Thanks!

On Dec 4, 2022, at 8:18 PM, Alexander Berger ***@***.***> wrote:

﻿

@nwebb-roux<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnwebb-roux&data=05%7C01%7Cwebb.nat%40northeastern.edu%7C1f486759301f4a8512c308dad65e8fa9%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C638057998875101417%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5iLX88ABJaYEMiUu8sive89LF6dPX8BojA4cl7Y88%2Bg%3D&reserved=0>, I think I got confused and mixed up our notebooks. I thought that this notebook<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fobservablehq.com%2Fd%2F0f11e85a1dccddcc&data=05%7C01%7Cwebb.nat%40northeastern.edu%7C1f486759301f4a8512c308dad65e8fa9%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C638057998875101417%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pX1s%2Bi%2BWP57A5LCjoZDf8Inug0qrfDxKpKb%2BPPdPqKw%3D&reserved=0> was the one we're using, but it does not seem to be.

Should I apply the changes you made in that fork back to the original one?
