### ISSUE TITLE
Navbar anchors scroll too far down for each anchor. 

### ISSUE THREAD

**Issue by bergsalex** [cs7290/stinky#21]
There's probably a setting in bootstrap to fix how the Navbar behaves in this situation. 

This issue is resolved when, after clicking a navbar item that links to a page anchor, the scrolling does not go so far as to cover the anchor content with the navbar.

**Comment by PhilipMathieu** [comment]
Looks like the best approach would be setting `scroll-margin-top` to the height of the navbar. There should be a way to do this in the SCSS, but I haven't worked it out yet.
