### ISSUE TITLE
To Dos

### ISSUE THREAD

**Issue by PhilipMathieu** [cs7290/stinky#3]
- Fork someone's code as a starting point (Lukas' version with Bootstrap 5 and Carousel?)
- Incorporate compass + histogram (Philip)
- Bootstrap messages (L)
- Clustering (A)
  - get the story (TBD) associated with a blob
- How to contribute to this dataset (smell-my-city)
- Update fairly quickly with an API (how long will it take to update the map)
  - https://github.com/CMU-CREATE-Lab/smell-pittsburgh-rails/wiki/Smell-PGH-API

**Comment by nwebb-roux** [comment]
I'm working on the API integration--I added a notebook to the class group in ObservableHQ but I'll try to work up a relevant PR this week

**Comment by PhilipMathieu** [comment]
I got booted off Zoom cuz my laptop went to sleep and now I'm stuck in the main room waiting for @pbnu to put me back in
